Step3-kakao-tech-campus/Team3_BE

.gitignore
src/main/java/com/bungaebowling/server/_core/config/Configs.java
src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
src/main/java/com/bungaebowling/server/_core/errors/exception/CustomException.java
src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception400.java
src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception401.java
src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception403.java
src/main/java/com/bungaebowling/server/_core/errors/exception/client/Exception404.java
src/main/java/com/bungaebowling/server/_core/errors/exception/server/Exception500.java
src/main/java/com/bungaebowling/server/_core/security/CustomSecurityFilterManager.java
src/main/java/com/bungaebowling/server/_core/security/CustomUserDetails.java
src/main/java/com/bungaebowling/server/_core/security/JwtAuthenticationFilter.java
src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
src/main/java/com/bungaebowling/server/_core/utils/ApiUtils.java
src/main/java/com/bungaebowling/server/_core/utils/ValidList.java
src/main/java/com/bungaebowling/server/_core/utils/cursor/CursorRequest.java
src/main/java/com/bungaebowling/server/_core/utils/cursor/PageCursor.java
src/main/java/com/bungaebowling/server/user/Role.java
src/main/java/com/bungaebowling/server/user/User.java
src/main/resources/application-private.yml.example
src/main/resources/application.yml

기본 configuration을 마쳐놓았습니다. 이제 api들을 바로 만들어도 될 거 같습니다.
프로젝트에 `spring security`를 포함시켰기 때문에 기본 설정을 하였습니다.
* `CORS`의 경우 `Configs `클래스에 허용하는 도메인들을 리스트로 작성하도록 분리시켜놨습니다.
* 일단 임시로` "*"`를 추가하여 모든 도메인에 대해 허용시켰습니다.
* jwt 생성 및 해석하는 클래스를 만들었습니다.
* jwt의 `SECRET`의 경우 `gitignore`로 관리하기 위해 `application-private.yml`을 추가로 만들었습니다.
* `application-private.yml.example`을 복사해 `application-private.yml`을 생성하여 사용하시면 됩니다.
* refresh 토큰의 경우, 임시로 작성해놨기 때문에 나중에 구현할 때 수정이 필요할 수 있습니다.
* access 토큰에 포함되는 정보는 user의 id(pk)와 role입니다.
* jwt 인증 필터를 `security filter`에 포함시켰습니다.
* 인증 실패 시 401, 권한 없을 시 403을 리턴하도록 필터에 핸들러를 추가하였습니다.
* Response 양식을 통일하기 위한 `Wrapper` 클래스를 만들었습니다.
* 추상 클래스 `CustomException`을 만들고 하위로 400, 401, 403, 404, 500 `Exception`을 만들었습니다.
* `GlobalExceptionHandler`로 `CustomException`들을 catch해 `errorResponse`를 주도록 …

프로젝트 security를 포함한 기본 config 설정 및 util 클래스 추가

---

build.gradle
docker-compose-redis.yml
src/main/java/com/bungaebowling/server/_core/config/RedisConfig.java
src/main/java/com/bungaebowling/server/_core/security/JwtAuthenticationFilter.java
src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
src/main/java/com/bungaebowling/server/_core/utils/ApiUtils.java
src/main/java/com/bungaebowling/server/user/User.java
src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
src/main/java/com/bungaebowling/server/user/service/UserService.java
src/main/resources/application-local.yml
src/main/resources/application-product.yml
src/main/resources/data.sql

redis의 경우 도커로 띄웠고, 액세스 토큰과 리프레시 토큰을 구현 완료 하였습니다. api 적인 관점에서는
- 회원가입
- 로그인
- 로그아웃
- 토큰 재발급
총 4가지의 api를 구현하였습니다.
redis의 경우 docker-compose-redis.yml을 통해 컨테이너를 만들었습니다. 개발/ 배포 profile에 전부 redis 설정을 집어 넣었습니다.
```sh
$ docker-compose -f docker-compose-redis.yml up
```
명령어로 레디스 컨테이너를 실행하실 수 있습니다. 혹은, intelliJ의 run configuration으로도 설정가능합니다.
redis에 직접 접근하여 값을 보고 싶은 경우,
```sh
$ docker exec -it redis redis-cli
127.0.0.1:6379> keys *
(empty array)
127.0.0.1:6379> keys *
1) "1"
127.0.0.1:6379> get 1
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwidHlwZSI6InJlZnJlc2giLCJleHAiOjE2OTgzNDc2NzR9.P71t6HS1NHKsUmTSpmthEnzN0Md2WMdbcTP10Udkg3N5kNOtjO8WgKQII3L2G8hF-Gw3TnvuoYXBOXfRVM3WKg"
127.0.0.1:6379> del 1
(integer) 1
127.0.0.1:6379> keys *
(empty array)
```
위와 같이 파악한 명령어는 `keys`, `get`, `del`이 있습니다. …

redis를 사용한 리프레시 토큰과 함께 인증 시퀀스 완성

---

src/main/java/com/bungaebowling/server/_core/config/MailConfig.java
src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
src/main/java/com/bungaebowling/server/user/User.java
src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
src/main/java/com/bungaebowling/server/user/service/UserService.java
src/main/resources/application-private.yml.example

인증 이메일 발송 및 이메일 인증으로 권한 증가 구현완료했습니다.
따로 메일 서버 만들기엔 아직 서버도 구축이 안되어 있어서 gmail을 활용하여 구현했습니다.
application-private.yml에 내용이 추가되었습니다. 여기에 gmail과 앱 비밀번호를 작성해야합니다.
gmail username은 bungaebowling55@gmail.com 이고 앱 비밀번호는 문의 주시면 알려드리겠습니다.
메일의 형태는 아직 다듬지 않아 단순히 링크만 전달하며 접속 할 프론트 화면이 구현되어 있어야합니다.
링크는 http://localhost:3000/email-verification?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwidHlwZSI6ImVtYWlsLXZlcmlmaWNhdGlvbiIsImV4cCI6MTY5NjEwMDgzNn0.MJMb2Q61AWtpzWs4Bw51Pd1OVBjLxQynub2lECfsYYaC2IhAjwUEJVmPHqng_YA-XSzq6eADof-k_nbDozvp7Q
이 형태이며 token 의 값을 이용해 /api/email-confirm으로 요청 시 user 권한 부여 일어나게 됩니다.
Issue Number: close #20

인증 이메일 발송을 통한 이메일 검사 구현

---

src/main/java/com/bungaebowling/server/applicant/Applicant.java
src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
src/main/java/com/bungaebowling/server/post/Post.java
src/main/java/com/bungaebowling/server/post/controller/PostController.java
src/main/java/com/bungaebowling/server/score/Score.java
src/main/java/com/bungaebowling/server/user/User.java
src/main/java/com/bungaebowling/server/user/rate/UserRate.java
src/main/java/com/bungaebowling/server/user/rate/repository/UserRateRepository.java

신청자 목록 조회 api의 응답 body를 수정하였습니다. 또한, rating을 계산해서 같이 주도록 변경하였으며, 기타 자잘한 버그들을 수정하였습니다.
- ApplicantResponse.GetApplicantsDto에 필요한 정보가 추가로 존재하여 개선하였습니다.
- 유저 ID를 함께 줍니다.
- 수락된 사람 수 / 전체 신청 수를 줍니다.
- select 문에서 로그인한 유저의 id가 where 절 안에 들어가는 문제를 수정하였습니다.
- 자신의 모집글인 경우만 신청자 목록을 확인할 수 있도록 권한 확인을 추하였습니다.
- 패키지명에 대문자가 작성되어있는 문제를 해결하였습니다.(score와 userRate)
- User안에 OneToMany를 추가하여 간단하게 rating 정보를 가져올 수 있도록 하였습니다.
- 하지만 이는 N + 1 문제가 남아있습니다.
- 신청자목록을 조회한 후 한번에 20개씩 조회한다고 하면 20개의 userRate에 접근하는 쿼리가 발생하게 됩니다.
- 구현의 용이성을 위해 일단은 이렇게 작성하고 넘어갑니다.
- ManyToOne에 FetchType.LAZY가 안적혀있는 문제를 해결했습니다.
- 이로 인해 쓸모없는 테이블까지 전부 Join되어 호출되고 있었습니다.
- OneToMany의 경우 기본이 LAZY fetch여서 추가하지 않았습니다.
- 모집글 작성 시 status는 201을 주는데 response body 내부에는 200으로 주던 문제를 해결했습니다.
Issue Number: close #21

신청자 목록 조회 응답 바디 수정 및 기타 버그 수정

---

src/main/java/com/bungaebowling/server/_core/errors/GlobalExceptionHandler.java
src/main/java/com/bungaebowling/server/comment/Comment.java
src/main/java/com/bungaebowling/server/comment/controller/CommentController.java
src/main/java/com/bungaebowling/server/comment/dto/CommentRequest.java
src/main/java/com/bungaebowling/server/comment/dto/CommentResponse.java
src/main/java/com/bungaebowling/server/comment/repository/CommentRepository.java
src/main/java/com/bungaebowling/server/comment/service/CommentService.java
src/main/resources/data.sql
src/main/resources/ddl.sql

댓글 api 구현 완료 하였습니다. 구현을 하며 더미 유저, 모집글, 댓글들을 살짝 추가하였습니다.(data.sql)
댓글의 경우는 회의의 결과에 따라 처음부터 created가 아닌 200 status를 주며 id를 리턴하도록 구현하였습니다.
또한 개발 과정에서 디버깅의 용이성을 위해 unkown Error에 대해 stackTrace를 출력하도록 ExceptionHandler에 추가해두었습니다.
- 댓글 테이블 선언에서 contentT로 잘못적혀있는 부분을 수정하며 서버의 mysql에도 오류 수정 반영하였습니다.
- 댓글 생성 api를 구현완료하였습니다.
- 대댓글 생성 api를 구현완료하였습니다.
- 댓글 조회 api를 구현 완료하였습니다.
- 모집글의 경우, 최근에 쓴 글이 최상위로 가지만, 댓글은 최근에 쓴 댓글이 최하위로 가게 됩니다.
- 삭제된 댓글에 대댓글이 있는 경우만, "삭제된 댓글입니다"/ 유저id null로 돌려줍니다.
- 그외, 대댓글이 없는 삭제된 댓글과 대댓글이 삭제된 경우의 댓글은 responseBody에 포함되어 내려가지 않습니다.
- size=20으로 요청이 왔다고 가정했을때, 대댓글이없는 삭제된 댓글이 5개 함께 db에서 조회된 경우 15개의 최상위 댓글만이 response로 돌아가게됩니다.
- 삭제된 댓글들로 인한 통일되지 않은 응답 개수 문제는,
- 프론트의 구현이 무한 스크롤로 이루어질 것입니다.
- 따라서 적은 개수가 응답되어도 자동으로 다음 key로 요청이 일어나 사용자 경험에 큰 영향을 주지 않습니다.
- 그렇기 때문에 무시해도 될 것 같아 이렇게 구현하였습니다.
- …

댓글 api 구현 완료

---

docker-compose.yml
src/main/java/com/bungaebowling/server/ServerApplication.java
src/main/resources/application-local.yml
src/main/resources/application-product.yml

서버 timezone을 맞췄습니다. 통신은 전부 KST 한국 시간으로 이루어 집니다.
[노션 서버 타임존 설정](https://www.notion.so/f00649087a574c3499bb5956e89aaee1) 에서 전체 과정을 볼 수 있습니다.
서버 및 MySQL, Spring boot의 시간대를 전부 KST(Asia/Seoul)로 변경하였습니다.
자바스크립트 테스트에서 Date 객체 직렬화 시 자동으로 UST로 변경되는 점을 확인하였고, 프론트에 요청하여 직접 "2023-10-06T22:10:00" `YYYY-MM-DDTHH:MM:SS` 형식으로 요청해달라고 전달하였습니다.
직접 문자열로 변환한 결과, 정상 작동한다는 결과를 프론트로부터 받았습니다.
Issue Number: close #29

서버 타임존 KST 설정

---

src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java

신청 취소 api에서 applicant id를 얻을 수 없다는 요청이 들어와서 신청 상태 조회 response에 applicantId를 추가했습니다. 변경 사항을 서버에 빠르게 반영하면 좋을 것 같습니다! 
- 사용자가 신청한 모집글을 신청 취소 하려면 신청 ID가 필요합니다. 신청 취소 기능을 위해 신청 상태 조회 api에 신청 id를 추가합니다. 신청을 하지 않았을 경우 null을 반환합니다. 
- 글 작성자를 applicant_tb에 추가하면서 신청자 목록 조회를 하면 글 작성자 정보도 전달되는 부분을 수정했습니다.  
Issue Number: #52

신청 상태 조회 api에 applicant id 추가

---

src/main/java/com/bungaebowling/server/applicant/controller/ApplicantController.java
src/main/java/com/bungaebowling/server/applicant/dto/ApplicantRequest.java
src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
src/main/resources/data.sql

게임 플레이 후의 별점 등록을 구현 완료하였습니다.
request 형태
```json
{
"targetId": 4,
"rating": 4
}
```
test@test.com으로 로그인 후 /api/posts/16/applicants/31/rating 으로 테스트 가능합니다.
---
사용자는 모집글에 대해 신청하고, 자신의 신청이 수락되었을 때, 게임 플레이 종료 후 자신의 신청 id를 사용하여 같이 플레이한 사람들에게 별점을 등록할 수 있습니다.
따라서 유효성 체크는 다음과 같습니다.
1. path의 신청id가 자신의 것이여야 합니다.
2. 자신의 신청이 수락된 상태(모집자가 승낙)여야 합니다.
3. 모집글이 모집완료(모집자가 마감 버튼 클릭; isClose 컬럼이 true)여야합니다.
4. 모집글의 시작시간 이후여야 합니다.(게임 플레이 시작 한 후부터 별점 가능)
아래는 requestBody에 대한 유효성입니다.
1. targetId는 같은 모집글에 신청한 유저의 id여야 합니다.
2. targetId가 신청한 신청은 수락된 상태여야 합니다.
3. targetId는 자신이면 안됩니다.
4. 별점은 1 ~ 5만 가능합니다.
---
추가적으로 더미 데이터를 추가하였습니다. 기본은 #41 의 테스트 데이터에 db 구조에 맞게 일부 수정을 가한 형태입니다.

별점 등록 api 구현

---

src/main/java/com/bungaebowling/server/message/controller/MessageController.java
src/main/java/com/bungaebowling/server/message/dto/MessageResponse.java
src/main/java/com/bungaebowling/server/message/repository/MessageRepository.java
src/main/java/com/bungaebowling/server/message/service/MessageService.java
src/test/java/com/bungaebowling/server/message/MessageRepositoryTest.java

대화방 목록 조회 수정
기존: 새로운메세지의 경우 유무만 알려줌 
수정: 새로운메세지의 수까지 알려줌
DTO 수정
- 각 상대방별 isNew -> countNew 로 변경: 기존에는 새로운 메시지 여부만 반환하였는데 새로운메시지수를 반환해 주는 것으로 변경
- 전체 countAll 삭제
- 전체 countNew 삭제
레포지토리 메소드 추가
- 상대방별 새로운 메세지 갯수 조회를 위한 메소드 추가
삭제된 레포지토리 메소드의 테스트 코드 삭제
+) 일대일대화방의 메소드 명을 변경 
getMessagesByOpponent() -> getMessagesAndUpdateToRead()
Issue Number:
close #50 close #44

쪽지API 대화방목록조회 수정

---

src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
src/main/java/com/bungaebowling/server/post/Post.java
src/main/java/com/bungaebowling/server/post/service/PostService.java
src/main/java/com/bungaebowling/server/post/service/PostSpecification.java

참여 기록 조회, 신청자 목록 버그를 수정했습니다.
- 참여 기록 조회에서 참석 확정 인원인 currentNumber를 post 엔티티에서 가져올 때, 데이터가 중복 조회되는 문제가 발생했습니다. jpql/querydsl을 사용하면 join/fetch join에서 OneToMany를 사용할 때 데이터가 중복 조회될 수 있다고 합니다!!! distinct()를 사용해서 중복을 제거했습니다. 
- 참여 기록 조회의 멤버에 참여 기록 조회 대상도 함께 넘겨줍니다.
- 참여 기록 조회에서 key 요청이 안되는 오류가 발생했습니다. 이것은 저의 실수로.. postIdLessThan()에서 id가 아닌 postId를 넘겨주고 있었습니다. 
- 신청자 목록 조회에서 글 작성자를 신청 테이블에 추가하면서 신청자 수를 가져올 때 +1 되는 버그가 발생했습니다. -1을 하기엔 좀 불안정한 것 같아서 query를 가져올 때 글 작성자일 경우를 제외하고 가져오도록 수정했습니다. 
Issue Number: close #59

참여 기록 조회, 신청자 목록 버그 수정

---

src/main/java/com/bungaebowling/server/score/service/ScoreService.java

점수 등록 API 관련 버그 수정입니다. 
- 점수만 등록했을 때
- 점수와 이미지(1개)를 등록했을 때 
기존의 코드에서 getSize() 부분을 제외하였습니다. 
- getSize가 file의 byte수를 체크하는 메소드이기 때문에, 잘못 사용된 코드라는 것을 알게 되어 해당 코드는 삭제했습니다. 
```
if (image.getSize() > 1) {
throw new CustomException(ErrorCode.SCORE_UPLOAD_FAILED, "점수는 1개씩 등록해주세요.");
}
```
- image null 체크에서는 image를 보내지 않으면, 해당 필드를 포함하지 않는다고 하여, 해당 부분을 참고해서 코드를 수정하였습니다. 
```
if (image == null) { 
... 
}
```
- 위의 코드들을 수정하면서 점수 숫자 등록에 대한 유효성 검사 코드가 없어, 0~300 사이의 숫자가 아닌 다른 숫자를 넣고 postman에서 test를 해보았을 때, 500 error로 잡는 것을 발견했습니다.
- 따라서, scoreNum이 0~300 사이의 수가 아닐 때, 유효성 검사를 추가하였습니다. 
```
if (scoreNum < 0 || scoreNum > 300) {
throw new CustomException(ErrorCode.SCORE_UPLOAD_FAILED, "0~300 사이의 숫자만 입력해주세요.");
}
```
Issue Number: #69

점수 등록 API 수정 

---

src/main/java/com/bungaebowling/server/_core/errors/GlobalValidationHandler.java
src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
src/main/java/com/bungaebowling/server/_core/utils/AwsS3Service.java
src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
src/main/java/com/bungaebowling/server/user/service/UserService.java
src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java

유저 통합 테스트 작성을 완료하였습니다. 테스트 코드 작성하며 발견한 이슈 #78 / #80 도 해결하였습니다.
각 api들의 테스트들을 작성하였습니다.
- GET /api/users
- 사용자 목록 조회에서 name에 null 허용을 하였습니다.(#78) null 일시 전체 검색합니다.
- null 일때와 검색어가 존재할 때에 대한 테스트 2개를 생성하였습니다.
- #79 이슈로 리턴되는 값 정렬에 대한 이슈를 생성하였습니다.
- GET /api/users/:userId
- GET /api/users/mine
- PUT /api/users/mine
- api 명세와 다르게 동작하며 api가 이상한 점을 발견했습니다.(#80)
- 점수 등록 쪽과 코드를 맞추기 위해 `@RequestParam`으로 변경하고 기타 로직들을 수정하여 해결하였습니다.(커밋 설명 참고)
- aws s3의 경우 mock처리하였습니다.
- GET /api/users/{userId}/records
Issue Number: #63, close #78, close #80

유저 통합 테스트 완성

---

src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
src/main/java/com/bungaebowling/server/score/Score.java
src/main/java/com/bungaebowling/server/score/controller/ScoreController.java
src/main/java/com/bungaebowling/server/score/service/ScoreService.java

점수 API를 개선하였습니다. 
- 점수 수정 API 개선 
- 점수 삭제 API 개선 
- 점수 이미지 삭제 API 추가 
점수 수정에 관해서 고려해야 할 사항은 총 7가지입니다. 
- case 1 : 점수(숫자)만 등록했을 때, 점수(숫자)만 수정 가능한지 
- case 2 : 점수(숫자)만 등록했을 때, 점수(숫자)수정 및 이미지 등록 가능한지 
- case 3 : 점수(숫자)만 등록했을 때, 수정 시 이미지만 등록 가능한지
- case 4 : 점수(숫자), 이미지 등록했을 때, 점수(숫자)만 수정 가능한지 
- case 5 : 점수(숫자), 이미지 등록했을 때, 이미지만 수정 가능한지 - **이미지 변경** 
- case 6 : 점수(숫자), 이미지 등록했을 때, 점수(숫자)수정 및 이미지 수정 가능한지 
- case 7 : 점수(숫자), 이미지 등록했을 때, 이미지 삭제할 수 있는지 - **이미지 삭제** 
위의 7가지 상황을 고려해서 점수 수정 API 코드를 개선해주었습니다. 
점수 이미지 삭제와 관련해서는 제가 직접 프론트 코드로 테스트 해본 결과 image를 빈 파일로 전달해주더라도 image 필드를 전달해주지 않는 것으로 확인이 되는 것 같아 점수 이미지 삭제 API를 따로 구현하는 것으로 변경하였습니다. 
점수 삭제와 관련해 점수(숫자)만 등록했을 경우, 점수가 삭제되지 않는 버그를 발견해 점수 이미지 여부에 관계없이 점수를 삭제해주는 상황을 반영하여 코드 수정했습니다. 
점수 이미지 삭제 API 추가하였습니다. 
```
DELETE …
```

점수 API 개선 

---

src/main/java/com/bungaebowling/server/user/service/UserService.java
src/test/java/com/bungaebowling/server/ControllerTestConfig.java
src/test/java/com/bungaebowling/server/GeneralApiResponseSchema.java
src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java

유저 컨트롤러에 대한 문서화를 완료하였습니다.
문서화는 복사 붙여넣기가 많다보니까 PR 분량 조절이 너무 어려운거 같습니다... swagger로 결과물 확인하시는게 나을거 같습니다.
https://server.jagaldol.dev:8080/api/docs/swagger 제 개인 서버에 먼저 올려두었습니다. 여기서 현재까지의 api 문서화를 확인하실 수 있습니다.
우여곡절이 많았는데, 일단 multipart/form-data의 경우 parameter 문서화가 안되서 직접 적었습니다.
- 관련 이슈: [Support for multipart parameter](https://github.com/ePages-de/restdocs-api-spec/issues/205)
그렇다고 하더라도 어떻게 전부 문서화 해놨고 쓸만한 거 같습니다.
저번에 이메일 보내는 테스트 mocking을 실패해서 주석 처리해놨었는데, 이것도 어떻게 해결하여 같이 문서화 하였습니다.
Issue Number: #63

유저 컨트롤러 문서화 완료

---

.env.example
build.gradle
k8s/backend.yaml
k8s/create-k8s-secret.sh
src/main/java/com/bungaebowling/server/_core/config/Configs.java
src/main/java/com/bungaebowling/server/_core/security/SecurityConfig.java
src/main/java/com/bungaebowling/server/post/controller/PostController.java
src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
src/main/java/com/bungaebowling/server/post/service/PostService.java
src/main/resources/application-deploy.yml
src/main/resources/application-local.yml
src/main/resources/application-product.yml
src/main/resources/application-test.yml

크램폴린을 사용하며 배포 주소가 잦게 변할 수 있으며, aws에 올라간 서버와 크램폴린에 올라간 서버에 전부 대응이 가능해야합니다. 이를 위해선 기존 하드코딩된 서버 주소 부분을 환경변수로 변경하고 환경변수로 주입하도록 변경하였습니다.
API_SERVER_URL이라는 환경변수를 만들었습니다.
window 환경에서 환경변수를 사용하기 편리하도록 build.gradle에는 .env 파일에서 직접 값을 읽는 방식으로 구현하였습니다.
- 쿠버네티스 환경에서는 .env 파일을 만들지 않고 환경변수를 등록하는 식으로 동작하기 때문에 추가적으로 환경변수를 읽고 .env가 있으면 그값을 사용하도록 구현하였습니다.
- 로컬에서 테스트하였을 때 .env가 없으면 환경변수로 등록된 값을 바탕으로 빌드되는 걸 테스트 완료하였습니다.
CORS에도 등록하였습니다. DOMAIN은 프론트(서비스 웹페이지) 주소이기 때문에 DOMAIN과 API_SERVER_URL을 둘다 등록하였습니다.
프론트 외에 API_SERVER_URL도 CORS에 등록해야하는 이유는 swagger에 백엔드 주소로 접근하기 때문입니다. swagger로 api 실행을 위해서는 백엔드의 도메인도 등록할 필요가 존재합니다.
https://server.jagaldol.dev:8080/api/docs/swagger 현재 환경변수로 동작하고 있습니다. 잘 동작하는 모습을 확인할 수 있습니다.
이번 PR 머지되면 bungae.jagaldol.dev 서버에도 동일하게 .env 세팅하도록 하겠습니다
.env에 대한 정보는 디스코드로 공유하겠습니다.

CORS 정보 environment variable로 주입

---

src/main/java/com/bungaebowling/server/comment/service/CommentService.java
src/main/resources/test_db/teardown.sql
src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
src/test/java/com/bungaebowling/server/_core/commons/GeneralParameters.java
src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java

댓글 조회에 대한 테스트 코드를 작성하였습니다. 작업을 하며 테스트 용 더미 데이터(댓글)을 추가하였고 유저 테스트에서 key와 size가 query parameter로 추가되지 않은 점을 고쳤습니다.
테스트 데이터에서 유저 2는 메일 인증이 안된 유저로 1, 3,4,5의 유저를 사용하여 더미 댓글을 생성하였습니다.
테스트를 하는 도중 댓글 api에 삭제된 댓글의 유저에 대한 null 처리가 안된 점을 발견하였고 수정하였습니다.
- 댓글의 경우 삭제 시 민감정보만 없애고 데이터는 남겨둡니다.
- 따라서 삭제된 댓글도 select가 가능하고 이때 댓글의 유저는 null로 되어 있습니다.
- 그렇기에 댓글 유저가 null 인경우에 대해 예외처리를 추가하였습니다.
사용자 목록 조회에서 key, size의 query parameter에 대해 작성되지 않은 점을 발견하였습니다.
- key, size를 사용하는 테스트를 하나 더 추가하여 해결하였습니다.
- 댓글 조회에서도 key와 size가 필요하여 만들었습니다.
key, size에 대한 문구등을 통일하고 한군데서 관리하여 재사용을 하기 위해 generalParameters Enum class를 만들었습니다.
기존의 ApiTag와 GeneralApiResponseSchema에 추가로 GeneralParameters까지 존재하니 지저분하여 _core.commons 패키지로 리팩토링하였습니다.
Issue Number: #63

댓글 조회 테스트 코드 작성 및 문서화 + 기타 버그 수정

---

src/main/java/com/bungaebowling/server/comment/Comment.java
src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java

댓글 등록, 대댓글 등록, 댓글 수정, 댓글 삭제를 추가하였습니다.
- 댓글 등록에 대한 테스트 생성도중 회원가입 시 id를 반환하지 않고 있던 버그를 발견해 수정하였습니다.
- 댓글 등록, 유저 등록, 모집글 등록 등등 생성 응답에 대한 General인 GeneralApiResponseSchema.CREATED를 추가하였습니다.
- 대댓글 등록에서 삭제된 댓글에 시도하는 실패 케이스를 추가하였습니다.
- 댓글 수정/삭제에서 자신의 것이 아닌 댓글에 시도하는 실패 케이스를 추가하였습니다.
Issue Number: #63

댓글 api 테스트 및 문서 작성 완료

---

src/main/java/com/bungaebowling/server/comment/Comment.java
src/main/java/com/bungaebowling/server/comment/service/CommentService.java
src/main/java/com/bungaebowling/server/place/service/PlaceService.java
src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/java/com/bungaebowling/server/user/dto/UserResponse.java
src/main/resources/test_db/teardown.sql
src/test/java/com/bungaebowling/server/_core/commons/ApiTag.java
src/test/java/com/bungaebowling/server/_core/commons/GeneralApiResponseSchema.java
src/test/java/com/bungaebowling/server/_core/commons/GeneralParameters.java
src/test/java/com/bungaebowling/server/city/controller/CityControllerTest.java
src/test/java/com/bungaebowling/server/comment/controller/CommentControllerTest.java
src/test/java/com/bungaebowling/server/user/controller/UserControllerTest.java

볼링장 상세 조회 api 에서 image를 넘겨줄 때 초기 요청 url에 google photo api key가 같이 전달됩니다. 구글 측에서 api key를 노출시키지 않는 url로 리다이렉트 시켜서 사용자에게 보여주기 때문에 리다이렉트된 이후 url을 가져와서 api key를 노출시키지 않도록 합니다.
getRedirectedUrl()에서 리다이렉트된 url을 가져옵니다. response header를 받아와야 하기 때문에 get 대신 exchange 메소드를 사용했습니다. http redirect를 비활성화해서 최종 목적지 200 response가 아닌 302 response를 가져오도록 설정합니다. 302의 response header에서 location을 가져와서 반환합니다. 
Issue Number: close #106

볼링장 이미지 url 수정

---

src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
src/main/java/com/bungaebowling/server/_core/security/JwtProvider.java
src/main/java/com/bungaebowling/server/user/User.java
src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
src/main/java/com/bungaebowling/server/user/service/UserService.java

- 비밀번호 변경 API를 추가하였습니다.
- 비밀번호 찾기(초기화) API를 추가하였습니다.
비밀번호 찾기 API를 구현 하면서 로직에 대해서 고민을 하였는데요. 현재 상태에서 가성비 좋게 구현하려고 방법을 생각하니 아래 3가지 방법이 떠올랐습니다.
1. (이메일, 지역코드) 를 입력 받아서 등록된 이메일로 임시 비밀번호를 발송해주는 방법
2. 메일인증 후 비밀번호를 메일로 보내는 방법
3. 2번과 유사한 방법이지만 메일을 2개 보내지 않고 비밀번호 정보는 따로 보여주는 페이지를 만든다.
결론적으로 2번 방식으로 구현을 하였습니다.
프론트쪽에서는 3가지 모두 그리 오래 걸리지 않는다고 하여 백엔드쪽의 결정에 따른다고 합니다.
1번의 경우 악의적으로 비밀번호초기화 공격을 할 가능성도 있기 때문에 2,3번 방법이 더욱 안정적이라 생각하였고
2,3 번의 경우 크게 차이는 없지만  2번방식이 조금 더 안정적인 것 같아 선택했습니다.
3번의 경우에는 메일에서 링크를 클릭하면 바로 새로운 창이 뜨면서 비밀번호를 보여주기 때문에 사용자 측면에서는 조금 더 자연스러울 수 있을 것 같습니다. 다만 리스폰스에 임시비밀번호가 담겨오기 때문에 보안쪽으로 문제가 없는지 걱정됩니다.(제 생각에는 크게 문제 없어보이긴합니다.)
2,3번 중에 어떠한 방식이 좋다고 생각하는지 궁금합니다.
수정하는게 크게 어렵지 않기 때문에 여러분들의 의견을 들어보고 수정 후 머지하겠습니다.
Issue Number:  close #104

비밀번호 관련 API 추가

---

src/main/java/com/bungaebowling/server/_core/errors/exception/ErrorCode.java
src/main/java/com/bungaebowling/server/_core/utils/CommonUtils.java
src/main/java/com/bungaebowling/server/post/dto/PostResponse.java
src/main/java/com/bungaebowling/server/post/service/PostService.java
src/main/java/com/bungaebowling/server/post/service/PostSpecification.java
src/main/java/com/bungaebowling/server/user/repository/UserRepository.java
src/main/java/com/bungaebowling/server/user/service/UserService.java

- 참여 기록 조회 distinct join fetch 이슈
- 프로필 수정 이름 중복 500 에러 이슈
- 프로필 수정 이미지 파일 index 이슈
위의 이슈들을 해결했습니다.
join fetch를 제거하고 distinct를 가져오는 쿼리를 분리했습니다. 
중복 이름 확인하고 try catch를 추가했습니다.
필드에 이미지가 첨부되지 않을 경우 index가 -1로 처리되는 오류가 발생했습니다. try catch에서 에러를 처리해줘서 이제는 큰 의미가 없는 것 같긴 하지만 안정성 있는 코드를 위해 index가 -1일 경우 예외를 처리하도록 수정했습니다. 점수 등록도 동일하게 변경했습니다.
Issue Number: close #102 
Issue Number: close #103
Issue Number: close #117

참여 기록 조회, 프로필 수정 버그 수정

---

src/main/resources/test_db/teardown.sql
src/test/java/com/bungaebowling/server/score/controller/ScoreControllerTest.java

ScoreController의 api들을 문서화 완료하였습니다.
- GET /api/posts/{postId}/scores
- POST /api/posts/{postId}/scores
- PUT /api/posts/{postId}/scores/{scoreId}
- DELETE /api/posts/{postId}/scores/{scoreId}
- DELETE /api/posts/{postId}/scores/{scoreId}/image
총 5개의 api를 문서화하였습니다.
Issue Number: #63

ScoreController api 문서화 완료

---

src/main/java/com/bungaebowling/server/user/controller/UserController.java
src/main/resources/application-deploy.yml
src/main/resources/application-product.yml

배포 환경에서 액세스 토큰을 10분 만료되도록 하였습니다.
또한 로그아웃 시 쿠키 삭제가 안되는 버그를 해결했습니다.
기존 배포가 2일의 액세스 만료가 설정되어 있어 10분으로 변경했습니다.
로그아웃할 때 리프레시 쿠키가 삭제가 안되는 걸 발견했고, secure과 http only를 추가로 붙여서 해결했습니다.
---
추가적으로 배포할 때, 현재 서버상에 토큰 TOKEN_SECRET이 기본값 그대로 들어가 있는 거 같습니다.
이거 무작위 문자열로 변경가능할까요?

토큰 관련 이슈 해결

---

src/main/java/com/bungaebowling/server/user/dto/UserRequest.java
src/main/java/com/bungaebowling/server/user/service/UserEmailCreator.java
src/main/java/com/bungaebowling/server/user/service/UserService.java

이메일 보내는 양식을 업데이트하였습니다.
위와 같이 변경되었습니다.
---
추가적으로 가입시 액세스 토큰을 줄 때, jpa에 save하면 columndefault로 role이 들어올 줄 알았는데 savedUser의 role이 null로 찍혀있어서 직접 role 넣었습니다.
이제 가입 시 액세스 토큰이 정상적으로 전달됩니다.

이메일 전송 양식 변경

---

src/main/resources/test_db/teardown.sql

시간 지남에 따른 테스트 실패에 대비해 테스트 데이터를 실행 시간에 종속화 시켰습니다.
H2 db 문법의 `DATEADD('DAY', 10, CURRENT_DATE())` 를 사용하여 테스트 실행 시간의 날짜에 맞게 데이터가 생성되도록 하였습니다.

테스트 데이터 업데이트
